### ISSUE TITLE
Variant Calling: Enable JointCalling subsequent to DRAGEN single calling

### ISSUE THREAD

**Issue by your-highness** [LaborBerlin/hum-dragen-routine#18]
**Background:**
To increase sensitivity of pedrigree-associated SNVs, CNVs and SVs calls and to make results compatible with VarFish ingestions a joint calling has to be done on single calling dragen results.

**Tasks:**
- [x] Implement Pedigree SNV VCF Calling [1]
- [x] Implement Pedigree CNV VCF Calling [2]
- [x] Implement Pedigree SV VCF Calling [3]

**References:**
[1] https://support-docs.illumina.com/SW/DRAGEN_v40/Content/SW/DRAGEN/JointAnalysis.htm
[2] https://support-docs.illumina.com/SW/DRAGEN_v40/Content/SW/MultisampleCNVCalling_fDG.htm
[3] https://support-docs.illumina.com/SW/DRAGEN_v40/Content/SW/StructuralVariantCalling.htm

**Comment by your-highness** [comment]
Thanks for your help @xiamaz on this topic!

**Comment by xiamaz** [comment]
Finished rewrite. Trio data should now be transferred to CUBI
