### ISSUE TITLE
Prototype a continuous validation strategy

### ISSUE THREAD

**Issue by your-highness** [LaborBerlin/hum-dragen-routine#35]
**Background:**
A continuous validation of analysis results is critical to ensure correctness of results. Opposed to the validation of gold standard data this works on metrics for real world data where no ground truth is necessary known. Still, threshold for certain qc criteria (_e.g._ number of variants, coverage thresholds, ...) can be inferred and checked against.

**Tasks:**
- [ ] Draft of quality report and initial qc criteria
- [ ] Coverage Statistics for Critical regions https://github.com/LaborBerlin/hum-dragen-routine/blob/master/resources/difficult_regions.bed
- [ ] Coverage Statistics for Exome regions
- [ ] Qualityscore-Distribution for SNVs, InDels, CNVs & SVs
- [ ] Performance Evaluation of _SNVs+InDels_ via `GATK VariantEval` [1] or `GATK Concordance` [2]
- [ ] Performance Evaluation of _CNVs_ via Ximmer approach [3]
- [ ] Performance Evaluation of _SVs_ via a Ximmer-_like_ approach [3]
- [ ] _For trios:_ Check genotype distributions in JointCalling VCFs for consanguinity

**References:**
[1] https://gatk.broadinstitute.org/hc/en-us/articles/9570243836187
[2] https://gatk.broadinstitute.org/hc/en-us/articles/9570484838043
[3] https://github.com/ssadedin/ximmer

**Comment by xiamaz** [comment]
Some comments regarding the needed work before report generation:
 
 Coverage Statistics for Critical regions https://github.com/LaborBerlin/hum-dragen-routine/blob/master/resources/difficult_regions.bed
- output already exists, just needs to be parsed, as the BED is already included in the executed germline pipeline
 Coverage Statistics for Exome regions
- output already exists, just needs to be adapted to use the BED +/- 50bp (as inside the resources folder), as this is the one being defined in our technical document
 Qualityscore-Distribution for SNVs, InDels, CNVs & SVs
- requires post-processing of generated SV/CNV files, as current CNV/SV metrics only give us the number of variants per type

 For trios: Check genotype distributions in JointCalling VCFs for consanguinity

# Technical comments

As of our current implementation, all these steps should run preferably run after an entire batch has been processed. Ximmer requires that a BAM file exists, so this would not allow us to delete data after processing.
